import 'package:flutter/material.dart';
import 'models.dart';

/// Mock data provider for Wardrobe Analytics UI
/// This provides sample data for UI development and testing
class MockAnalyticsData {
  static WardrobeAnalyticsData get sampleData => WardrobeAnalyticsData(
        categoryDistribution: CategoryDistribution(
          categories: [
            const CategoryData(name: 'Tops', count: 25, percentage: 35.7, color: '#FF6F61'),
            const CategoryData(name: 'Bottoms', count: 18, percentage: 25.7, color: '#FFD700'),
            const CategoryData(name: 'Dresses', count: 12, percentage: 17.1, color: '#87CEEB'),
            const CategoryData(name: 'Outerwear', count: 8, percentage: 11.4, color: '#98FB98'),
            const CategoryData(name: 'Shoes', count: 7, percentage: 10.0, color: '#DDA0DD'),
          ],
        ),
        colorPalette: [
          const ColorData(colorHex: '#000000', itemCount: 15, percentage: 21.4),
          const ColorData(colorHex: '#FFFFFF', itemCount: 12, percentage: 17.1),
          const ColorData(colorHex: '#FF6F61', itemCount: 8, percentage: 11.4),
          const ColorData(colorHex: '#4169E1', itemCount: 7, percentage: 10.0),
          const ColorData(colorHex: '#32CD32', itemCount: 6, percentage: 8.6),
          const ColorData(colorHex: '#FFD700', itemCount: 5, percentage: 7.1),
          const ColorData(colorHex: '#FF69B4', itemCount: 4, percentage: 5.7),
          const ColorData(colorHex: '#8A2BE2', itemCount: 3, percentage: 4.3),
          const ColorData(colorHex: '#FF4500', itemCount: 3, percentage: 4.3),
          const ColorData(colorHex: '#20B2AA', itemCount: 2, percentage: 2.9),
          const ColorData(colorHex: '#F0E68C', itemCount: 2, percentage: 2.9),
          const ColorData(colorHex: '#CD853F', itemCount: 3, percentage: 4.3),
        ],
        wearFrequency: [
          const WearFrequencyData(itemName: 'Black Jeans', wearCount: 15, category: 'Bottoms'),
          const WearFrequencyData(itemName: 'White T-Shirt', wearCount: 12, category: 'Tops'),
          const WearFrequencyData(itemName: 'Denim Jacket', wearCount: 8, category: 'Outerwear'),
          const WearFrequencyData(itemName: 'Blue Dress', wearCount: 7, category: 'Dresses'),
          const WearFrequencyData(itemName: 'Sneakers', wearCount: 10, category: 'Shoes'),
          const WearFrequencyData(itemName: 'Coral Blouse', wearCount: 6, category: 'Tops'),
          const WearFrequencyData(itemName: 'Black Pants', wearCount: 9, category: 'Bottoms'),
          const WearFrequencyData(itemName: 'Summer Dress', wearCount: 4, category: 'Dresses'),
        ],
        totalItems: 70,
        averageWearCount: 6.3,
      );

  static List<Insight> get sampleInsights => [
        const Insight(
          id: '1',
          title: 'Most Worn Category: Tops',
          description: 'You wear tops 35% more than other categories. Consider diversifying with more dresses or accessories.',
          actionType: InsightActionType.viewItems,
          isFavorite: true,
          icon: Icons.trending_up,
          priority: 'high',
        ),
        const Insight(
          id: '2',
          title: 'Color Gap: You Need More Colors',
          description: 'Your wardrobe is dominated by black and white items. Adding more colorful pieces could enhance your style variety.',
          actionType: InsightActionType.shoppingList,
          isFavorite: false,
          icon: Icons.palette_outlined,
          priority: 'medium',
        ),
        const Insight(
          id: '3',
          title: 'Underused Items Alert',
          description: '12 items in your wardrobe haven\'t been worn in the last 3 months. Consider styling them differently or donating.',
          actionType: InsightActionType.viewItems,
          isFavorite: false,
          icon: Icons.warning_outlined,
          priority: 'low',
        ),
        const Insight(
          id: '4',
          title: 'Perfect Outfit Opportunity',
          description: 'Your coral blouse pairs perfectly with your black jeans and denim jacket for a trendy casual look.',
          actionType: InsightActionType.createOutfit,
          isFavorite: true,
          icon: Icons.auto_awesome_outlined,
          priority: 'medium',
        ),
        const Insight(
          id: '5',
          title: 'Missing Essential: Professional Blazer',
          description: 'Based on your lifestyle, a professional blazer would complete 15+ outfit combinations in your wardrobe.',
          actionType: InsightActionType.addToWardrobe,
          isFavorite: false,
          icon: Icons.business_center_outlined,
          priority: 'high',
        ),
        const Insight(
          id: '6',
          title: 'Seasonal Transition Ready',
          description: 'Your wardrobe is well-prepared for the current season with appropriate layering pieces.',
          actionType: InsightActionType.none,
          isFavorite: false,
          icon: Icons.check_circle_outline,
          priority: 'low',
        ),
      ];

  static List<ShoppingGuideItem> get sampleShoppingGuide => [
        const ShoppingGuideItem(
          id: '1',
          title: 'Professional Blazer',
          description: 'A versatile navy or black blazer to complete your professional looks and add sophistication to casual outfits.',
          category: 'Outerwear',
          priority: 'essential',
          aiQuery: 'professional blazer navy black versatile work casual',
          tags: ['professional', 'versatile', 'essential'],
        ),
        const ShoppingGuideItem(
          id: '2',
          title: 'Statement Necklace',
          description: 'Add visual interest to your solid-colored tops with a bold statement necklace in gold or silver.',
          category: 'Accessories',
          priority: 'recommended',
          aiQuery: 'statement necklace gold silver bold accessories',
          tags: ['accessories', 'statement', 'versatile'],
        ),
        const ShoppingGuideItem(
          id: '3',
          title: 'Colorful Cardigan',
          description: 'A bright cardigan in coral, emerald, or royal blue to add color variety to your neutral wardrobe.',
          category: 'Tops',
          priority: 'recommended',
          aiQuery: 'colorful cardigan coral emerald blue bright layering',
          tags: ['color', 'layering', 'cozy'],
        ),
        const ShoppingGuideItem(
          id: '4',
          title: 'Classic Trench Coat',
          description: 'A timeless trench coat for transitional weather that works with both casual and professional outfits.',
          category: 'Outerwear',
          priority: 'essential',
          aiQuery: 'classic trench coat timeless professional casual',
          tags: ['classic', 'timeless', 'weather'],
        ),
        const ShoppingGuideItem(
          id: '5',
          title: 'Patterned Scarf',
          description: 'A silk scarf with patterns to add texture and visual interest to solid-colored outfits.',
          category: 'Accessories',
          priority: 'optional',
          aiQuery: 'patterned scarf silk texture visual interest',
          tags: ['patterns', 'texture', 'accent'],
        ),
        const ShoppingGuideItem(
          id: '6',
          title: 'Midi Skirt',
          description: 'A flowy midi skirt in a flattering color to create more feminine silhouettes and outfit variety.',
          category: 'Bottoms',
          priority: 'recommended',
          aiQuery: 'midi skirt flowy feminine flattering variety',
          tags: ['feminine', 'versatile', 'flattering'],
        ),
        const ShoppingGuideItem(
          id: '7',
          title: 'Ankle Boots',
          description: 'Versatile ankle boots in brown or black leather to transition outfits between seasons.',
          category: 'Shoes',
          priority: 'essential',
          aiQuery: 'ankle boots brown black leather versatile seasonal',
          tags: ['shoes', 'versatile', 'seasonal'],
        ),
        const ShoppingGuideItem(
          id: '8',
          title: 'Crossbody Bag',
          description: 'A structured crossbody bag in a neutral color for hands-free convenience and polished look.',
          category: 'Accessories',
          priority: 'recommended',
          aiQuery: 'crossbody bag structured neutral hands-free polished',
          tags: ['practical', 'polished', 'everyday'],
        ),
      ];
}
